config:
    send_anonymous_usage_stats: false
    
beer_analytics:
    target: dev
    outputs:
        beer_demo:
            type: '{{ env_var("DBT_KBC_DBT_BEER_TYPE") }}'
            user: '{{ env_var("DBT_KBC_DBT_BEER_USER") }}'
            password: '{{ env_var("DBT_KBC_DBT_BEER_PASSWORD") }}'
            schema: '{{ env_var("DBT_KBC_DBT_BEER_SCHEMA") }}'
            warehouse: '{{ env_var("DBT_KBC_DBT_BEER_WAREHOUSE") }}'
            database: '{{ env_var("DBT_KBC_DBT_BEER_DATABASE") }}'
            account: '{{ env_var("DBT_KBC_DBT_BEER_ACCOUNT") }}'
            threads: 4
